# LLM配置
llm:
  # 默认使用的LLM
  default: "OpenAI"
  
  # 可用的LLM列表
  providers:
    OpenAI:
      name: "OpenAI"
      endpoint: "https://api.openai.com/v1/chat/completions"
      api_key: "your_openai_api_key"
      model: "gpt-4-vision-preview"
      max_tokens: 1000
      temperature: 0.7
      system_prompt: "你是一个专业的视频脚本编剧。请根据提供的图片，创作一段详细的视频脚本或旁白。描述应该包含场景、情感、动作和故事情节，以便能够用于生成高质量的视频。"
    
    Claude:
      name: "Claude"
      endpoint: "https://api.anthropic.com/v1/messages"
      api_key: "your_anthropic_api_key"
      model: "claude-3-opus-20240229"
      max_tokens: 1000
      temperature: 0.7
      system_prompt: "你是一个专业的视频脚本编剧。请根据提供的图片，创作一段详细的视频脚本或旁白。描述应该包含场景、情感、动作和故事情节，以便能够用于生成高质量的视频。"
    
    openai-api-compatible:
      name: "openai-api-compatible"
      endpoint: "https://your-openai-compatible-api-endpoint/v1/chat/completions"
      api_key: "your_api_key"
      model: "your_model_name"
      max_tokens: 1000
      temperature: 0.7
      system_prompt: "你是一个专业的视频脚本编剧。请根据提供的图片，创作一段详细的视频脚本或旁白。描述应该包含场景、情感、动作和故事情节，以便能够用于生成高质量的视频。"
      image_format: "base64"
      vision_api: true
      api_version: ""
      organization: ""

# 视频生成模型配置
video_generator:
  # 默认使用的视频生成模型
  default: "kling"
  
  # 可用的视频生成模型列表
  providers:
    kling:
      name: "可灵(kling)"
      endpoint: "https://api.klingai.com"
      access_key: "your_kling_access_key"
      secret_key: "your_kling_secret"
      model: "kling-v1-5"
      max_duration: 5  # 秒

# 日志配置
logging:
  level: "INFO"
  file: "logs/app.log"
  rotation: "10 MB"
  retention: "1 month"
